### PR TITLE
Debian package

### PR DESCRIPTION
**Pull request by shtrom**
RFP/ITP at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905883

Builds with
```
dpkg-buildpackage --no-sign
```
until I work out how to make it use my key.

### CODE REVIEW

**Comment by gkdr** [comment]
i have read that the packaging files should NOT reside in the same repo. do you know anything about this matter?

**Comment by shtrom** [comment]
I've seen both, but I think that outside of the repo is preferred. Though some packaging is better thai none (:

I think either lurch of carbon have been packaged separately in Debian since this PR was created. It might be worth checking how they did it.
-- 
Olivier Mehani <shtrom@ssji.net>
Sent from my mobile, please excuse my brevity.

**Comment by jre-wine** [comment]
> I think either lurch of carbon have been packaged separately in Debian since this PR was created. It might be worth checking how they did it.

Indeed luckily both have been packaged in Debian and are available there since a few weeks now:
https://tracker.debian.org/pkg/purple-lurch
https://tracker.debian.org/pkg/purple-xmpp-carbons

Thanks everyone!

**Comment by jre-wine** [comment]
> i have read that the packaging files should NOT reside in the same repo. do you know anything about this matter?

Yes, generally it is preferred to have no debian/ directory in upstream's (your) releases. But with modern packaging practices it doesn't really matter anymore, because it just gets discarded and replaced by Debian's debian/ dir.

**Comment by gkdr** [comment]
first off, thanks for the contribution, @shtrom. sorry it took me so long to reply at all.

@jre-wine thanks for clarifying. so since it's already packaged, it probably does not make sense to merge this?

**Comment by shtrom** [comment]
On 6 December 2020 7:49:10 am AEDT, Richard Bayerle <notifications@github.com> wrote:
>first off, thanks for the contribution, @shtrom. sorry it took me so
>long to reply at all.
>
>@jre-wine thanks for clarifying. so since it's already packaged, it
>probably does not make sense to merge this?

Yup. No worries.
-- 
Olivier Mehani <shtrom@ssji.net>
Sent from my mobile, please excuse my brevity.

**Comment by jre-wine** [comment]
@gkdr thanks. From the perspective from Debian and Tails I think there is indeed no need for a debian/ packaging here. Just continue to work with them if they bring up something specific.

**Comment by gkdr** [comment]
i'm closing this then. thanks for the clarification @jre-wine, and thanks for your contribution (and patience) @shtrom :slightly_smiling_face:

**Pull request closed without merging**
